DROP TABLE IF EXISTS venues CASCADE;
DROP TABLE IF EXISTS bands CASCADE;
DROP TABLE IF EXISTS tours CASCADE;


CREATE TABLE venues (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255),
	address VARCHAR(255),
	lat FLOAT(53),
	lng FLOAT(53),
	food_type VARCHAR(255)
);

CREATE TABLE bands (
 	id SERIAL PRIMARY KEY,
  	password_digest VARCHAR NOT NULL,
  	name VARCHAR(255)
);

CREATE TABLE tours (
	id SERIAL PRIMARY KEY,
	tour_date VARCHAR(255),
	venue_id INTEGER REFERENCES venues,
	band_id INTEGER REFERENCES bands
);